server:
    port: 29602

eureka:
    client:
        service-url:
            defaultZone: http://localhost:29600/eureka
    instance:
        appname: api-gateway
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 10

spring:
    application:
        name: api-gateway
    servlet:
        multipart:
            enabled: true   # 启用http上传处理
            max-file-size: 100MB # 设置单个文件的最大长度
            max-request-size: 100MB # 设置最大的请求文件的大小
            file-size-threshold: 10MB  # 当上传文件达到1MB的时候进行磁盘写入
    output:
        ansi:
            enabled: always
    rabbitmq:
            host: hins.work
            port: 5672
            username: admin
            password: admin
