server:
  port: 29601

spring:
  application:
    name: zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:29600/eureka/
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 10

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    api-gateway: /api/**
    upload-service: /upload/**

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  httpclient:
    enabled: false
  okhttp:
    enabled: true